import React from 'react' // eslint-disable-line
import Theatre from '../src/react-components/index.js'
import { createRoot } from 'react-dom/client'

const reactRootId = 'root'
const container = document.getElementById(reactRootId)
const root = createRoot(container)

const objectJson = [
  {
    id: 'video-001',
    type: 'VIDEO',
    src:
      'https://storage.googleapis.com/statics-readr-tw-dev/files/test-e0u6aXKDeeLbFrNXXCi.mp4',
  },
  {
    id: 'video-002',
    type: 'VIDEO',
    src:
      'https://storage.googleapis.com/statics-readr-tw-dev/files/ckyh3qlyc000010xr3knicohe-ezXZiJ6mIf7NdADTRgYN.mp4',
  },
]

const animateJson = {
  sheetsById: {
    Scene: {
      staticOverrides: {
        byObject: {
          'video-001': {
            position: { x: 23.333333333333332, y: 13.048780487804878 },
            size: { width: 300, height: 200 },
            visible: true,
            isPlaying: true,
            isLoop: false,
            scale: 1,
            zIndex: '10',
          },
          'video-002': {
            position: { x: 50.69444444444444, y: 39.146341463414636 },
            size: { width: 300, height: 200 },
            visible: true,
            isPlaying: true,
            isLoop: false,
            scale: 1,
            zIndex: '10',
          },
        },
      },
    },
  },
  definitionVersion: '0.4.0',
  revisionHistory: [],
}

const mobileObjectJson = [
  {
    id: 'img-001',
    type: 'IMAGE',
  },
  {
    id: 'bg-001',
    type: 'BACKGROUND',
  },
  {
    id: 'img-002',
    type: 'IMAGE',
  },
  {
    id: 'font-001',
    type: 'FONT',
  },
  {
    id: 'img-003',
    type: 'IMAGE',
  },
  {
    id: 'font-002',
    type: 'FONT',
  },
  {
    id: 'video-001',
    src:
      ' https://editools.readr.tw/files/e-a-e-e-2023-08-03-ae-a-8-33-21-tXAhv1ZX7dDPTMdPYwv.mov',
    type: 'VIDEO',
  },
]

const mobileAnimateJson = {
  sheetsById: {
    Scene: {
      sequence: {
        type: 'PositionalSequence',
        length: 10,
        tracksByObject: {
          'img-001': {
            trackData: {
              '0y0z2chjAh': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'TIiOSQFB66',
                    type: 'bezier',
                    value: 16.72051696284329,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["position","x"]',
              },
              '4MKjSsryhc': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'JnSlghM38b',
                    type: 'bezier',
                    value: 841,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["size","width"]',
              },
              '9awNqpsWcu': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'G0RpEmpjij',
                    type: 'bezier',
                    value: '10',
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["zIndex"]',
              },
              DGLCzT2fD8: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'IWrJYODd9g',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["scale"]',
              },
              GuPmy4vRVw: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'cTOHKJnNZu',
                    type: 'bezier',
                    value:
                      'https://editools-gcs.readr.tw/images/cfa9b54a-a295-44c2-a9e7-9ac896e80751.png',
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["url"]',
              },
              K7GaB9ENnD: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'Z2dw4h9yy1',
                    type: 'bezier',
                    value: -0.20188425302826116,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["position","y"]',
              },
              'X7-kxQ-Ju1': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'dRguP9CT0W',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 1.233,
                    connectedRight: true,
                  },
                  {
                    id: 'k6nwubX_pZ',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["visible"]',
              },
              cARc8wU7T6: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '_BfKSdTyGs',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["opacity"]',
              },
              fqlDhAg7GX: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'Ee438F_G6L',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["border","radius"]',
              },
              lMsVxe8GYs: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'VLB_rDNs5l',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["border","size"]',
              },
              wzrvmDITHN: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '6FgT5tDl5G',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 3.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-001:["border","color"]',
              },
            },
            trackIdByPropPath: {
              '["url"]': 'GuPmy4vRVw',
              '["scale"]': 'DGLCzT2fD8',
              '["zIndex"]': '9awNqpsWcu',
              '["opacity"]': 'cARc8wU7T6',
              '["visible"]': 'X7-kxQ-Ju1',
              '["position","x"]': '0y0z2chjAh',
              '["position","y"]': 'K7GaB9ENnD',
              '["size","width"]': '4MKjSsryhc',
              '["border","size"]': 'lMsVxe8GYs',
              '["border","color"]': 'wzrvmDITHN',
              '["border","radius"]': 'fqlDhAg7GX',
            },
          },
          'img-002': {
            trackData: {
              'Fz6Of-WkQD': {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["border","size"]',
              },
              Hxv5ke13CR: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["size","width"]',
              },
              K8oFZ9lbNl: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["zIndex"]',
              },
              NGcTS2o2FC: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["border","radius"]',
              },
              WHnFXu2JQm: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["position","y"]',
              },
              WhF1jefuSm: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'FqGKWJdnXy',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'UXHhSNyzso',
                    type: 'bezier',
                    value: false,
                    handles: [0.5, 1, 0.5, 0],
                    position: 1.233,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-002:["visible"]',
              },
              atg77VZfIT: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["scale"]',
              },
              o1KGWKhbs0: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["border","color"]',
              },
              qH5tB4ok2N: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["opacity"]',
              },
              tpR9IajTA2: {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["position","x"]',
              },
              'wSxIx6D-0K': {
                type: 'BasicKeyframedTrack',
                keyframes: [],
                __debugName: 'img-002:["url"]',
              },
            },
            trackIdByPropPath: {
              '["url"]': 'wSxIx6D-0K',
              '["scale"]': 'atg77VZfIT',
              '["zIndex"]': 'K8oFZ9lbNl',
              '["opacity"]': 'qH5tB4ok2N',
              '["visible"]': 'WhF1jefuSm',
              '["position","x"]': 'tpR9IajTA2',
              '["position","y"]': 'WHnFXu2JQm',
              '["size","width"]': 'Hxv5ke13CR',
              '["border","size"]': 'Fz6Of-WkQD',
              '["border","color"]': 'o1KGWKhbs0',
              '["border","radius"]': 'NGcTS2o2FC',
            },
          },
          'img-003': {
            trackData: {
              '4Q0tu4EPcj': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '0B7imoLq_d',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: 'bFCmcfUJU2',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["border","size"]',
              },
              '5KuVJWBsIQ': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'D5CykB0uis',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: '2ay8fDXoJ_',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["opacity"]',
              },
              NqxvpRGliy: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'oPU0SHselh',
                    type: 'bezier',
                    value: 15.616307162981313,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: 'd8kFV2ddG7',
                    type: 'bezier',
                    value: 15.616307162981313,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["position","x"]',
              },
              UY9guCDSef: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'bmf05_x9HE',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: '4EcBww7b6K',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["scale"]',
              },
              UZdwOkjo50: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '9eZtmmq_6V',
                    type: 'bezier',
                    value: -0.20588235294117752,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: '2qVHWCh2iT',
                    type: 'bezier',
                    value: -0.20588235294117752,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                  {
                    id: 'HpZYNL4QO_',
                    type: 'bezier',
                    value: -100,
                    handles: [0.5, 1, 0.5, 0],
                    position: 6,
                    connectedRight: true,
                  },
                  {
                    id: 'qhq75JA0Et',
                    type: 'bezier',
                    value: -1000,
                    handles: [0.5, 1, 0.5, 0],
                    position: 6.433,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["position","y"]',
              },
              VLajxr1OON: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'LOa3vVhgq7',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: 'K4418oPNrh',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["border","color"]',
              },
              f8a0zBTw6m: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'U0Qo6OCUg5',
                    type: 'bezier',
                    value: '10',
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: 'dj5cn4PqX6',
                    type: 'bezier',
                    value: '10',
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["zIndex"]',
              },
              g7Gs_ZqrIL: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'P-TMBkQO6M',
                    type: 'bezier',
                    value: 954.5,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: '1VEmWI4SRI',
                    type: 'bezier',
                    value: 954.5,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["size","width"]',
              },
              okvzoJTNsL: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'Yh5G3CBXjH',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: 'aymbIa7LYV',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["border","radius"]',
              },
              qCvePPPoN8: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '0kbcUcrVAP',
                    type: 'bezier',
                    value: false,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.367,
                    connectedRight: true,
                  },
                  {
                    id: 'eU5Xzvw8n5',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: 'aMb_da4keV',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["visible"]',
              },
              zQ9WpTNVEM: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'T3HJkV3q3C',
                    type: 'bezier',
                    value:
                      'https://editools-gcs.readr.tw/images/c6a8f0f6-4385-4d91-8c63-7d97d024a360.png',
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                  {
                    id: 'hMWbjBHpvq',
                    type: 'bezier',
                    value:
                      'https://editools-gcs.readr.tw/images/c6a8f0f6-4385-4d91-8c63-7d97d024a360.png',
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.467,
                    connectedRight: true,
                  },
                  {
                    id: 'VoX_AazTAH',
                    type: 'bezier',
                    value:
                      'https://editools-gcs.readr.tw/images/c6a8f0f6-4385-4d91-8c63-7d97d024a360.png',
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                  {
                    id: 'WN7ihNBkst',
                    type: 'bezier',
                    value:
                      'https://editools-gcs.readr.tw/images/c6a8f0f6-4385-4d91-8c63-7d97d024a360.png',
                    handles: [0.5, 1, 0.5, 0],
                    position: 6,
                    connectedRight: true,
                  },
                ],
                __debugName: 'img-003:["url"]',
              },
            },
            trackIdByPropPath: {
              '["url"]': 'zQ9WpTNVEM',
              '["scale"]': 'UY9guCDSef',
              '["zIndex"]': 'f8a0zBTw6m',
              '["opacity"]': '5KuVJWBsIQ',
              '["visible"]': 'qCvePPPoN8',
              '["position","x"]': 'NqxvpRGliy',
              '["position","y"]': 'UZdwOkjo50',
              '["size","width"]': 'g7Gs_ZqrIL',
              '["border","size"]': '4Q0tu4EPcj',
              '["border","color"]': 'VLajxr1OON',
              '["border","radius"]': 'okvzoJTNsL',
            },
          },
          'font-001': {
            trackData: {
              '0OscmcKqkF': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '-vL4UFlDR3',
                    type: 'bezier',
                    value: 56,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: '_qVjhbt0nz',
                    type: 'bezier',
                    value: 56,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'elXSd78plB',
                    type: 'bezier',
                    value: 56,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["position","x"]',
              },
              '0mHyjfMY6w': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '6CE5Hf_fco',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'OJLJ8f2C4-',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'BOaNexq40o',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["visible"]',
              },
              '6L8ET2IjdZ': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'ul6hN5J318',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'FVwn0d1xL7',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: '5Uesi52bH1',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["bgColor"]',
              },
              BZGuW3zZpB: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'gIpjTA78Yd',
                    type: 'bezier',
                    value: 100.02691790040377,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'E2eCZzkqUY',
                    type: 'bezier',
                    value: 32.48183041722746,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: '1ikyFhVe1B',
                    type: 'bezier',
                    value: -36.02422611036339,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["position","y"]',
              },
              DXTj_Tzi8P: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'ZjqbqDsnfY',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: '-Zo18jaQ0K',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'fN6fz0uIMv',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["opacity"]',
              },
              'ExfV7R6U-e': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'FdWLqD-U8V',
                    type: 'bezier',
                    value: 300,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'IiyDalUNBX',
                    type: 'bezier',
                    value: 300,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 's4WX8gyS0V',
                    type: 'bezier',
                    value: 300,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["size","width"]',
              },
              HQCl6Iv76j: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'uQYyQdEvLw',
                    type: 'bezier',
                    value: 27,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'GWs54Eh7pm',
                    type: 'bezier',
                    value: 27,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'UCQKy81tWY',
                    type: 'bezier',
                    value: 27,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["lineHeight"]',
              },
              IlSrq85GH3: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '_gnQqbCMZV',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 1,
                      g: 1,
                      r: 1,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'w5bnGi-gPr',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 1,
                      g: 1,
                      r: 1,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'nVgLJxTd5e',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 1,
                      g: 1,
                      r: 1,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["font","color"]',
              },
              NeGWZkhgtD: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'Ln0vA53s3c',
                    type: 'bezier',
                    value: 'justify',
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: '9GBLN-ggr4',
                    type: 'bezier',
                    value: 'justify',
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: '_GJgPxXVSz',
                    type: 'bezier',
                    value: 'justify',
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["textAlign"]',
              },
              'X229JE-tOC': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'oWjQ0b9ozO',
                    type: 'bezier',
                    value: 32,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'ynDrhzAEMg',
                    type: 'bezier',
                    value: 32,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'bv8eA_9zyh',
                    type: 'bezier',
                    value: 32,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["padding"]',
              },
              X_A34ST2Tr: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'ILARMyi9V1',
                    type: 'bezier',
                    value: 16,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'iZY1DnQ_mp',
                    type: 'bezier',
                    value: 16,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'oVGcWWx-pf',
                    type: 'bezier',
                    value: 16,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["font","size"]',
              },
              '_Bar-yrp0z': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'e5B4T0AzN3',
                    type: 'bezier',
                    value: 4,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'irPWuNbXwI',
                    type: 'bezier',
                    value: 4,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'DJ12bSWE4h',
                    type: 'bezier',
                    value: 4,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["border","radius"]',
              },
              a83plrJmTX: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'IRZ7Wfr8La',
                    type: 'bezier',
                    value: 200,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'COAlohKdD-',
                    type: 'bezier',
                    value: 200,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'Ql_OmCdVxf',
                    type: 'bezier',
                    value: 200,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["font","weight"]',
              },
              edD_IrqNgx: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '9LRbEl1Lyu',
                    type: 'bezier',
                    value:
                      '在所有的 Deepfake 假訊息中，「原始來源就說是假的」的 Deepfake 影片佔了整體很大一部分，且集中在早期。這類的假訊息在發佈的時候就告知讀者這是假影片。',
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'ebjxtVtcYs',
                    type: 'bezier',
                    value:
                      '在所有的 Deepfake 假訊息中，「原始來源就說是假的」的 Deepfake 影片佔了整體很大一部分，且集中在早期。這類的假訊息在發佈的時候就告知讀者這是假影片。',
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'CS8DZRUOHM',
                    type: 'bezier',
                    value:
                      '在所有的 Deepfake 假訊息中，「原始來源就說是假的」的 Deepfake 影片佔了整體很大一部分，且集中在早期。這類的假訊息在發佈的時候就告知讀者這是假影片。',
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["content"]',
              },
              'lciM-r_wW9': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'pQlJ892J4V',
                    type: 'bezier',
                    value: '100',
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'Cy3QIe9Ndz',
                    type: 'bezier',
                    value: '100',
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'MGP4jFVtX0',
                    type: 'bezier',
                    value: '100',
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["zIndex"]',
              },
              lf_Fra7YNd: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'rvFK-9GAka',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'NOeHgKdIY3',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'SackTWvrQf',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["scale"]',
              },
              'pckIc_LM-1': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'o6STmFqAwQ',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'JNYqOyimAN',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'WclqL_4Diz',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["border","size"]',
              },
              qxiqPws8H_: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'h4i9REmWLY',
                    type: 'bezier',
                    value: 0.6,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: '68UF7wH1c5',
                    type: 'bezier',
                    value: 0.6,
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'Ym_tXDJuOa',
                    type: 'bezier',
                    value: 0.6,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["font","spacing"]',
              },
              zZTCfOylov: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'Vy28ENsxs-',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 0,
                    connectedRight: true,
                  },
                  {
                    id: 'LBUsVWzEcl',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 0.633,
                    connectedRight: true,
                  },
                  {
                    id: 'HpPtYi5uqr',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-001:["border","color"]',
              },
            },
            trackIdByPropPath: {
              '["scale"]': 'lf_Fra7YNd',
              '["zIndex"]': 'lciM-r_wW9',
              '["bgColor"]': '6L8ET2IjdZ',
              '["content"]': 'edD_IrqNgx',
              '["opacity"]': 'DXTj_Tzi8P',
              '["padding"]': 'X229JE-tOC',
              '["visible"]': '0mHyjfMY6w',
              '["textAlign"]': 'NeGWZkhgtD',
              '["lineHeight"]': 'HQCl6Iv76j',
              '["font","size"]': 'X_A34ST2Tr',
              '["font","color"]': 'IlSrq85GH3',
              '["position","x"]': '0OscmcKqkF',
              '["position","y"]': 'BZGuW3zZpB',
              '["size","width"]': 'ExfV7R6U-e',
              '["border","size"]': 'pckIc_LM-1',
              '["font","weight"]': 'a83plrJmTX',
              '["border","color"]': 'zZTCfOylov',
              '["font","spacing"]': 'qxiqPws8H_',
              '["border","radius"]': '_Bar-yrp0z',
            },
          },
          'font-002': {
            trackData: {
              '4RuDSfStzg': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'q1J7k9MJbg',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'JG-KK2oJLz',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'yOt3rcbApH',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'RWfGzQ0V7I',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["border","color"]',
              },
              '5-cdkxHIGO': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'DavT94eeRq',
                    type: 'bezier',
                    value: 'justify',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'QMEg-uemo3',
                    type: 'bezier',
                    value: 'justify',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'y-kfOBkGq6',
                    type: 'bezier',
                    value: 'justify',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'WRD9HTt1ZC',
                    type: 'bezier',
                    value: 'justify',
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["textAlign"]',
              },
              '6TrYguhO1w': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'YyC-HLbG7N',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'tCwmDi85B9',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'OEB1DK-ORj',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'Ej7gO12c4k',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["scale"]',
              },
              '9ARralaJPt': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'akeSWxhGA-',
                    type: 'bezier',
                    value: 27,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'w7l5XxN8p5',
                    type: 'bezier',
                    value: 27,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'p9uM6MTrkr',
                    type: 'bezier',
                    value: 27,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'YqCN4fVx94',
                    type: 'bezier',
                    value: 27,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["lineHeight"]',
              },
              A2YurnmPCi: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'NAVm3EO1UQ',
                    type: 'bezier',
                    value: 4,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: '3QDdPrjOkN',
                    type: 'bezier',
                    value: 4,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: '1oS2eXagTb',
                    type: 'bezier',
                    value: 4,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'tGb6eBhwPO',
                    type: 'bezier',
                    value: 4,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["border","radius"]',
              },
              DTMscPCNfN: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'zdbTRCB554',
                    type: 'bezier',
                    value: 56,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'vdHg2SHLrm',
                    type: 'bezier',
                    value: 56,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'hlprxJY0V9',
                    type: 'bezier',
                    value: 56,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'HsCJfa9dqU',
                    type: 'bezier',
                    value: 56,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["position","x"]',
              },
              Ddn8qSj62_: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'VA6MM4AdZ0',
                    type: 'bezier',
                    value: 16,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'X87-IkpDk_',
                    type: 'bezier',
                    value: 16,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'hw0A8YZPd2',
                    type: 'bezier',
                    value: 16,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'qIWmN99pfn',
                    type: 'bezier',
                    value: 16,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["font","size"]',
              },
              HMex5THCqC: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'H_6o8AR288',
                    type: 'bezier',
                    value: '100',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'n-Xozqkahr',
                    type: 'bezier',
                    value: '100',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'Z0wsC3s1tw',
                    type: 'bezier',
                    value: '1000',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'RNpW0czNP0',
                    type: 'bezier',
                    value: '100',
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["zIndex"]',
              },
              KsfVtaTFNW: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '_iaXkOrSYa',
                    type: 'bezier',
                    value:
                      '美國前總統歐巴馬的語出驚人吸引了百萬人觀看，但這個影片是美國媒體《Buzzfeed》和知名影星皮爾（Jordan Peele）製作的。',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'WiMbLVSQP_',
                    type: 'bezier',
                    value:
                      '美國前總統歐巴馬的語出驚人吸引了百萬人觀看，但這個影片是美國媒體《Buzzfeed》和知名影星皮爾（Jordan Peele）製作的。',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'XxGmjVZ1to',
                    type: 'bezier',
                    value:
                      '美國前總統歐巴馬的語出驚人吸引了百萬人觀看，但這個影片是美國媒體《Buzzfeed》和知名影星皮爾（Jordan Peele）製作的。',
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'wi6kxw7kJo',
                    type: 'bezier',
                    value:
                      '美國前總統歐巴馬的語出驚人吸引了百萬人觀看，但這個影片是美國媒體《Buzzfeed》和知名影星皮爾（Jordan Peele）製作的。',
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["content"]',
              },
              RTv9d15udc: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'v8rmkCgMDb',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: '2LOlVWFWIu',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'woKP_AJn9E',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'gLd8ULOgCX',
                    type: 'bezier',
                    value: 0,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["border","size"]',
              },
              UFQzs2L2bA: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'VdCN28rY5S',
                    type: 'bezier',
                    value: 100,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'Y_hJvVPKG2',
                    type: 'bezier',
                    value: 39.72633220705285,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'xq2Wr6rVC-',
                    type: 'bezier',
                    value: 39.74071325901661,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'tCVd410sYw',
                    type: 'bezier',
                    value: -26.5,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["position","y"]',
              },
              UZSK4tkn7W: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'kteI3jZPLX',
                    type: 'bezier',
                    value: 300,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'S1pFxLuwdy',
                    type: 'bezier',
                    value: 300,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'duSa-xzcQ0',
                    type: 'bezier',
                    value: 300,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'KtcgrMd_1c',
                    type: 'bezier',
                    value: 300,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["size","width"]',
              },
              Xk19cSkOEk: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'tYL0m8IVls',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 1,
                      g: 1,
                      r: 1,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'MhOzqwjud_',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0.9999997702872695,
                      g: 0.9999999826692539,
                      r: 1,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'l08hYmlWCW',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0.9999996353974726,
                      g: 0.9999999724924497,
                      r: 1,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: '6XYLpeSHKy',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 1,
                      g: 1,
                      r: 1,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["font","color"]',
              },
              cTjYxPKVUG: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'WsvDxHAzwV',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'Lbl9V-KUoq',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'DKzME7YRwY',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'QbInirb07H',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["visible"]',
              },
              eHt6Pzsk6F: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '2uoEZFHxLi',
                    type: 'bezier',
                    value: 200,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: '_NCO3nDUJg',
                    type: 'bezier',
                    value: 200,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'QyhMKZk05n',
                    type: 'bezier',
                    value: 200,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: '96TgD4i1WQ',
                    type: 'bezier',
                    value: 200,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["font","weight"]',
              },
              ezmw_3IrHt: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'hZf23fKC_o',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'oDxychI-Op',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: '0cGnWik06d',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'K6-U71g9ps',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["opacity"]',
              },
              nurszACBAh: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'bgsNeiIBHe',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: '0R2hYejVcr',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: '-33crH4cYV',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'IP6y287zkK',
                    type: 'bezier',
                    value: {
                      a: 1,
                      b: 0,
                      g: 0,
                      r: 0,
                    },
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["bgColor"]',
              },
              rgt6xEVkxC: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '7ULis9-WMO',
                    type: 'bezier',
                    value: 0.6,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'ubrxdUDewL',
                    type: 'bezier',
                    value: 0.6,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: 'W1OjLcE921',
                    type: 'bezier',
                    value: 0.6,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'xXJBnz2Ox1',
                    type: 'bezier',
                    value: 0.6,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["font","spacing"]',
              },
              xOy2yv5HYR: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'I4WrTodRq7',
                    type: 'bezier',
                    value: 32,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4,
                    connectedRight: true,
                  },
                  {
                    id: 'Efz26YLQzo',
                    type: 'bezier',
                    value: 32,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                  {
                    id: '39N6q8tZjU',
                    type: 'bezier',
                    value: 32,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.9,
                    connectedRight: true,
                  },
                  {
                    id: 'yAcFOjCczY',
                    type: 'bezier',
                    value: 32,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'font-002:["padding"]',
              },
            },
            trackIdByPropPath: {
              '["scale"]': '6TrYguhO1w',
              '["zIndex"]': 'HMex5THCqC',
              '["bgColor"]': 'nurszACBAh',
              '["content"]': 'KsfVtaTFNW',
              '["opacity"]': 'ezmw_3IrHt',
              '["padding"]': 'xOy2yv5HYR',
              '["visible"]': 'cTjYxPKVUG',
              '["textAlign"]': '5-cdkxHIGO',
              '["lineHeight"]': '9ARralaJPt',
              '["font","size"]': 'Ddn8qSj62_',
              '["font","color"]': 'Xk19cSkOEk',
              '["position","x"]': 'DTMscPCNfN',
              '["position","y"]': 'UFQzs2L2bA',
              '["size","width"]': 'UZSK4tkn7W',
              '["border","size"]': 'RTv9d15udc',
              '["font","weight"]': 'eHt6Pzsk6F',
              '["border","color"]': '4RuDSfStzg',
              '["font","spacing"]': 'rgt6xEVkxC',
              '["border","radius"]': 'A2YurnmPCi',
            },
          },
          'video-001': {
            trackData: {
              'I-fIQ90Go0': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'NcI5C7T7pS',
                    type: 'bezier',
                    value: 284,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.567,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["size","width"]',
              },
              K8RMRa8MDN: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'G62-p2Xw4F',
                    type: 'bezier',
                    value: '100',
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.567,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["zIndex"]',
              },
              OdkUxebK3F: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'Thpqqa9wRz',
                    type: 'bezier',
                    value: 155.5,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.567,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["size","height"]',
              },
              STD0d5_P0o: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'K7n4uLrCIq',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.567,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["isPlaying"]',
              },
              bwdxik3LQ2: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '-3MdO1tD3C',
                    type: 'bezier',
                    value: false,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.3,
                    connectedRight: true,
                  },
                  {
                    id: '7zoaMM14n5',
                    type: 'bezier',
                    value: true,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.367,
                    connectedRight: true,
                  },
                  {
                    id: 'dF3rsHz3E_',
                    type: 'bezier',
                    value: false,
                    handles: [0.5, 1, 0.5, 0],
                    position: 5.5,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["visible"]',
              },
              'e36SEe-0o8': {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '4SGtBQNoNg',
                    type: 'bezier',
                    value: 39.33747412008281,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.567,
                    connectedRight: true,
                  },
                  {
                    id: 'OXoKfn2GVF',
                    type: 'bezier',
                    value: 39.33747412008281,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["position","x"]',
              },
              fwvKezyNlg: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: '2PriqBIWiD',
                    type: 'bezier',
                    value: 16.94117647058824,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.567,
                    connectedRight: true,
                  },
                  {
                    id: 'GL2qeCFVYf',
                    type: 'bezier',
                    value: 16.94117647058824,
                    handles: [0.5, 1, 0.5, 0],
                    position: 4.4,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["position","y"]',
              },
              wlfjjFHUzD: {
                type: 'BasicKeyframedTrack',
                keyframes: [
                  {
                    id: 'BVwpxydSzn',
                    type: 'bezier',
                    value: 1,
                    handles: [0.5, 1, 0.5, 0],
                    position: 2.567,
                    connectedRight: true,
                  },
                ],
                __debugName: 'video-001:["scale"]',
              },
            },
            trackIdByPropPath: {
              '["scale"]': 'wlfjjFHUzD',
              '["zIndex"]': 'K8RMRa8MDN',
              '["visible"]': 'bwdxik3LQ2',
              '["isPlaying"]': 'STD0d5_P0o',
              '["position","x"]': 'e36SEe-0o8',
              '["position","y"]': 'fwvKezyNlg',
              '["size","width"]': 'I-fIQ90Go0',
              '["size","height"]': 'OdkUxebK3F',
            },
          },
        },
        subUnitsPerUnit: 30,
      },
      staticOverrides: {
        byObject: {
          'bg-001': {
            url:
              'https://editools-gcs.readr.tw/images/31f7c721-78bd-4ebd-8f5c-82ade8ff97f2.png',
          },
          'img-001': {
            url:
              'https://editools-gcs.readr.tw/images/cfa9b54a-a295-44c2-a9e7-9ac896e80751.png',
            size: {
              width: 841,
            },
            scale: 1,
            border: {
              size: 0,
              color: {
                a: 1,
                b: 0,
                g: 0,
                r: 0,
              },
              radius: 0,
            },
            zIndex: '10',
            opacity: 1,
            visible: false,
            position: {
              x: 16.72051696284329,
              y: -0.20188425302826116,
            },
          },
          'img-002': {
            url:
              'https://editools-gcs.readr.tw/images/0638a6ab-fb3a-4d97-bc7a-e4b6b9c2cced.png',
            size: {
              width: 841,
            },
            scale: 1,
            border: {
              size: 0,
              color: {
                a: 1,
                b: 0,
                g: 0,
                r: 0,
              },
              radius: 0,
            },
            zIndex: '10',
            opacity: 1,
            visible: true,
            position: {
              x: 16.72051696284329,
              y: -0.202,
            },
          },
          'img-003': {
            url:
              'https://editools-gcs.readr.tw/images/8698120c-f1fa-4952-9541-488cd747b239.png',
            size: {
              width: 841,
            },
            scale: 1,
            border: {
              size: 0,
              color: {
                a: 1,
                b: 0,
                g: 0,
                r: 0,
              },
              radius: 0,
            },
            zIndex: '10',
            opacity: 1,
            visible: true,
            position: {
              x: 16.720516962843288,
              y: 0.14705882352941133,
            },
          },
          'font-001': {
            font: {
              size: 16,
              color: {
                a: 1,
                b: 1,
                g: 1,
                r: 1,
              },
              weight: 200,
              spacing: 0.6,
            },
            size: {
              width: 300,
            },
            scale: 1,
            border: {
              size: 0,
              color: {
                a: 1,
                b: 0,
                g: 0,
                r: 0,
              },
              radius: 4,
            },
            zIndex: '100',
            bgColor: {
              a: 1,
              b: 0,
              g: 0,
              r: 0,
            },
            content:
              '在所有的 Deepfake 假訊息中，「原始來源就說是假的」的 Deepfake 影片佔了整體很大一部分，且集中在早期。這類的假訊息在發佈的時候就告知讀者這是假影片。',
            opacity: 1,
            padding: 32,
            visible: true,
            position: {
              x: 57.52827140549273,
              y: 35.5585464333782,
            },
            textAlign: 'justify',
            lineHeight: 27,
          },
          'font-002': {
            font: {
              size: 16,
              color: {
                a: 1,
                b: 1,
                g: 1,
                r: 1,
              },
              weight: 200,
              spacing: 0.6,
            },
            size: {
              width: 300,
            },
            scale: 1,
            border: {
              size: 0,
              color: {
                a: 1,
                b: 0,
                g: 0,
                r: 0,
              },
              radius: 4,
            },
            zIndex: '100',
            bgColor: {
              a: 1,
              b: 0,
              g: 0,
              r: 0,
            },
            content:
              '美國前總統歐巴馬的語出驚人吸引了百萬人觀看，但這個影片是美國媒體《Buzzfeed》和知名影星皮爾（Jordan Peele）製作的。',
            opacity: 1,
            padding: 32,
            visible: true,
            position: {
              x: 56,
              y: 41.1764705882353,
            },
            textAlign: 'justify',
            lineHeight: 27,
          },
        },
      },
    },
  },
  revisionHistory: [],
  definitionVersion: '0.4.0',
}

root.render(
  <Theatre
    objectJson={objectJson}
    animateJson={animateJson}
    mobileObjectJson={mobileObjectJson}
    mobileAnimateJson={mobileAnimateJson}
    type="video"
  />
)
