import DroppingText from '../src/react-components/index.js'
import React from 'react' // eslint-disable-line
import { createRoot } from 'react-dom/client'

const reactRootId = 'root'
const container = document.getElementById(reactRootId)
const root = createRoot(container)

const mockTextArr = [
  '十幾天沒有',
  '<span style="color: #F85F5F">服用精神病</span>',
  '症的<span style="font-size: 3em;">藥</span>。',
  '土地重劃後',
  '知自己名下',
  '地坪減少後',
  '，有明顯的',
  '土地被侵占',
  '<span style="font-size: 3em;">妄想</span>。',
  '小學三年級',
  '時領有重度',
  '智能不足殘',
  '障手冊。',
  '不規則的門',
  '診<span style="font-size: 3em;">求醫</span>行為',
  '，衝動控制',
  '能力低，因',
  '此造成自我',
  '工作、人際',
  '關係降低、',
  '<span style="color: #F85F5F">需他人照顧</span>',
  '他一直在吵',
  '我，害我不',
  '能睡覺，我',
  '的情緒沒法',
  '控制',
  '<span style="color: #F85F5F">他不認得我</span>',
  '們是他的小',
  '孩，以為我',
  '們是別人。',
  '他把平常用',
  '的<span style="font-size: 3em;">剪刀</span>、縫',
  '衣針擺在那',
  '裡，就是要',
  '<span style="font-size: 2em;">對我不利</span>。',
  '他們一直想',
  '<span style="font-size: 3em;">殺我</span>，不放',
  '過我，我也',
  '<span style="color: #F85F5F">受不了</span>。',
  '<span style="color: #F85F5F">他們害了我</span>',
  '好幾十年。',
  '出院後，未',
  '再回院門診',
  '<span style="font-size: 2em;">追蹤治療</span>。',
  '出現認知、',
  '情感、人際',
  '關係及衝動',
  '控制改變等',
  '<span style="font-size: 3em;">病態</span>狀態。',
  '平日工作不',
  '穩定，經常',
  '收集垃圾，',
  '社交及工作',
  '<span style="color: #F85F5F">能力日漸退</span>',
  '<span style="color: #F85F5F">化。</span>',
  '未按時吃<span style="font-size: 3em;">藥</span>',
  '而病情轉劇',
  '，並有自言',
  '語、自笑、',
  '亂撿東西等',
  '<span style="font-size: 2em;">異常行為</span>。',
  '未規則接受',
  '治療，生活',
  '功能、社會',
  '功能逐漸退',
  '<span style="color: #F85F5F">化。</span>',
  '母親拒絕和',
  '我有任何互',
  '動。',
  '生活安排能',
  '力亦不理想',
  '，常騎腳踏',
  '車在外閒晃',
  '，社會功能',
  '有明顯下降',
  '的傾向',
  '<span style="color: #F85F5F">用火燒我自。</span>',
  '<span style="color: #F85F5F">己的身體。</span>，',
  '治療我內心',
  '的<span style="font-size: 3em;">創傷</span>。',
  '伊常講我壞',
  '話、要<span style="font-size: 2em;">設計</span>',
  '我。',
  '因堅信自己',
  '<span style="color: #F85F5F">被監視監聽。</span>',
  '，而不斷想',
  '用電鑽挖出',
  '牆內的監視',
  '監聽設備。',
  '因飲酒後情',
  '緒不穩、憂',
  '<span style="font-size: 3em;">鬱</span>發作。',
  '因<span style="font-size: 3em;">經濟因素</span>',
  '而未繼續就',
  '醫治療。',
  '因<span style="font-size: 3em;">精神疾病</span>',
  '發作被<span style="font-size: 2em;">強制</span>',
  '<span style="font-size: 3em;">送醫治療</span>，',
  '治療似未完',
  '全即自動出',
  '院',
  '<span style="color: #F85F5F">在浴室大叫。</span>',
  '、在窗前自',
  '言<span style="font-size: 3em;">自語</span>',
  '多年來斷續',
  '有<span style="font-size: 3em;">幻聽</span>及被',
  '害意念，且',
  '不甚規則治',
  '療，症狀起',
  '起伏伏。',
  '有人坐在車',
  '子<span style="font-size: 2em;">指使我</span>。',
  '有人要<span style="font-size: 3em;">追殺</span>',
  '我。',
  '有色情<span style="font-size: 3em;">妄想</span>',
  '、被害<span style="font-size: 3em;">妄想</span>',
  '、思考邏輯',
  '不佳、衝動',
  '控制力差等',
  '問題。',
  '有時會跟隨',
  '聲音於半夜',
  '<span style="color: #F85F5F">四處遊蕩</span>，',
  '<span style="color: #F85F5F">而自己無法</span>',
  '<span style="color: #F85F5F">控制自己</span>不',
  '聽從聲音指',
  '令。',
  '自幼理解、',
  '學習、表達',
  '與社交溝通',
  '能力差，需',
  '<span style="color: #F85F5F">要母親協助</span>',
  '，在國二時',
  '更出現<span style="font-size: 3em;">拒學</span>',
  '情形',
  '<span style="font-size: 3em;">我又<span style="font-size: 3em;">沒病</span></span>、',
  '要吃<span style="font-size: 3em;">藥</span>你自',
  '己吃。',
  '我不知道對',
  '方有受傷。',
  '<span style="color: #F85F5F">我不是在縱</span>',
  '<span style="color: #F85F5F">火，</span>而是在',
  '燒東西。',
  '我只是想回',
  '去上課。',
  '我在點衛生',
  '紙，把它當',
  '作金紙在燒',
  '，泡到水裡',
  '面在洗臉。',
  '我沒再吃<span style="font-size: 3em;">藥</span>',
  '了，因為我',
  '<span style="font-size: 3em;">沒病</span>。',
  '我是來救地',
  '球人的、快',
  '點讓我出去',
  '<span style="font-size: 3em;">救人</span>，有壞',
  '人要害我',
  '我是<span style="font-size: 3em;">皇帝</span>、',
  '鬼尊，很人',
  '想害我，在',
  '我腦袋裡放',
  '<span style="font-size: 3em;">符咒</span>，放了',
  '二十幾年。',
  '我是神明觀',
  '世音<span style="font-size: 2em;">菩薩</span>，',
  '與<span style="font-size: 2em;">保生大帝</span>',
  '、媽祖有密',
  '切關係。',
  '我們從小頭',
  '腦不好、同',
  '學看我們不',
  '起、全部人',
  '都打我一個',
  '、<span style="font-size: 2em;">沒人管我</span>',
  '們。',
  '我被社區管',
  '委會欺壓許',
  '久，再加上',
  '<span style="color: #F85F5F">兩天都沒睡</span>',
  '覺，我心情',
  '<span style="font-size: 3em;">鬱</span>悶。',
  '我想到過去',
  '的一些不開',
  '心的事情就',
  '<span style="font-size: 3em;">發作了</span>。',
  '我當時沒想',
  '那麼多，因',
  '為<span style="color: #F85F5F">太太上吊</span>',
  '過世，又長',
  '期失業，心',
  '情不好',
  '我懷疑丈夫',
  '<span style="color: #F85F5F">要害死我，</span>',
  '因此不斷逃',
  '跑',
  '車禍腦傷之',
  '後，陸續出',
  '現類似癲癇',
  '及精神方面',
  '的症狀。',
  '其因精神障',
  '礙、長期幻',
  '聽，致對於',
  '外界認知能',
  '力受損，無',
  '法收集充分',
  '資訊。',
  '其思考、',
  '情緒與行為',
  '應已達到直',
  '接受<span style="font-size: 3em;">妄想</span>及',
  '<span style="font-size: 3em;">幻聽</span>控制。',
  '明知其長年',
  '罹患長期慢',
  '性躁<span style="font-size: 3em;">鬱</span>病，',
  '卻未積極、',
  '適切治療。',
  '近三年來並',
  '未好好接受',
  '規律性的治',
  '療，加以工',
  '作不順利，',
  '情緒一直處',
  '於<span style="font-size: 3em;">低落</span>。',
  '長年遭受當',
  '地居民言語',
  '騷擾、謾罵',
  '及恐嚇。',
  '長期不定期',
  '在身心醫學',
  '科看診，經',
  '診斷為憂<span style="font-size: 3em;">鬱</span>',
  '症。',
  '長期處於被',
  '害<span style="font-size: 3em;">妄想</span>，心',
  '中存有隨時',
  '警覺被毒害',
  '<span style="color: #F85F5F"><span style="font-size: 3em;">死亡</span>的擔憂</span>',
  '<span style="font-size: 2em;">與恐懼</span>',
  '長期罹患思',
  '覺失調症，',
  '其疾病已呈',
  '現慢性化並',
  '損害其認知',
  '功能。',
  '持續呈現易',
  '怒情緒、防',
  '衛態度，甚',
  '至經常拒絕',
  '服<span style="font-size: 3em;">藥</span>。',
  '拿後照鏡照',
  '<span style="font-size: 3em;">蛇妖。</span>',
  '案發前中斷',
  '治療超過半',
  '年。',
  '案發前服<span style="font-size: 3em;">藥</span>',
  '中斷 1',
  '年。',
  '病程已經超',
  '過 2 年',
  '。',
  '<span style="color: #F85F5F">缺乏病識感</span>',
  '，且仍有幻',
  '覺經驗干擾',
  '。',
  '從小在不健',
  '全的環境下',
  '成長。',
  '情緒混亂很',
  '生氣，控制',
  '不住。',
  '被告未就診',
  '而停<span style="font-size: 3em;">藥</span>。',
  '被監控<span style="font-size: 3em;">妄想</span>',
  '。',
  '陸續間歇出',
  '現<span style="font-size: 3em;">幻聽</span>、妄',
  '想症狀。',
  '幾年前於台',
  '大醫院精神',
  '科門診過，',
  '但未能規律',
  '回診及配合',
  '服<span style="font-size: 3em;">藥</span>',
  '曾被家人強',
  '制帶至他院',
  '住院治療，',
  '<span style="color: #F85F5F">對此憤恨不</span>',
  '平。',
  '發生不順遂',
  '的事情，一',
  '定是循理會',
  '相關的人構',
  '陷或刻意造',
  '成',
  '當時騎機車',
  '去找朋友，',
  '但覺得路變',
  '得不一樣，',
  '雙手被外力',
  '控制而無法',
  '控制速度。',
  '<span style="color: #F85F5F">經商失敗，</span>',
  '有所挫折，',
  '目前在開計',
  '程車，且近',
  '數月來，對',
  '許多事常會',
  '<span style="font-size: 3em;">胡思亂想</span>。',
  '對他人的不',
  '信任感與防',
  '衛態度加，',
  '人際關係益',
  '加緊張。',
  '與弟弟衝突',
  '後，被送去',
  '臺大醫院加',
  '護病房，自',
  '此開始不規',
  '則地接受精',
  '神科診療。',
  '憂<span style="font-size: 3em;">鬱</span>症常發',
  '作，常有自',
  '殺行為。',
  '罹患慢性思',
  '覺失調症迄',
  '今，至少已',
  '逾二十年。',
  '罹患精神分',
  '裂症，但中',
  '斷治療。',
  '頻繁報警並',
  '時有言語、',
  '肢體衝突。',
  '<span style="font-size: 2em;">離家出走</span>兩',
  '年半時間，',
  '在外遊蕩精',
  '神恍惚。',
  '懶得花時間',
  '在垃圾身上',
  '。',
  '<span style="font-size: 3em;">藥</span>物順從性',
  '不佳、家庭',
  '支持亦差，',
  '無法讓接受',
  '穩定而完整',
  '的治療。',
  '覺得母親很',
  '多疑，刻意',
  '針對自己。',
  '邏輯鬆散，',
  '判斷力、衝',
  '動控制不佳',
  '。',
  '人際互動長',
  '期疏離，獨',
  '來獨往。',
  '工作及生活',
  '不順遂，皆',
  '因爲別人以',
  '特殊能力干',
  '擾、控制他',
  '。',
  '半夜覺得有',
  '<span style="color: #F85F5F">人掐其脖子</span>',
  '。',
  '企圖利用法',
  '院將我送入',
  '<span style="font-size: 3em;">精神病院</span>。',
  '全身都在痛',
  '，四處求診',
  '，有人在整',
  '我。',
  '因生意失敗',
  '及家庭重大',
  '變故，患有',
  '憂<span style="font-size: 3em;">鬱</span>症。',
  '在長期<span style="font-size: 3em;">藥</span>物',
  '治療後，仍',
  '有聽幻覺、',
  '<span style="font-size: 3em;">妄想</span>症狀。',
  '<span style="color: #F85F5F">有人傷害我</span>',
  '。',
  '長年罹患「',
  '器質性精神',
  '病」。',
  '長期酒精成',
  '癮',
  '長期憂<span style="font-size: 3em;">鬱</span>企',
  '圖自殺。',
  '害怕會發瘋',
  '、<span style="font-size: 3em;">死亡</span>。',
  '案發前一如',
  '以往上班，',
  '並無異樣。',
  '<span style="color: #F85F5F">病史20年</span>',
  '。',
  '常常歇斯底',
  '里，不吃<span style="font-size: 3em;">藥</span>',
  '的話不能控',
  '制自己。',
  '被害意念，',
  '已接近<span style="font-size: 3em;">妄想</span>',
  '程度。',
  '意識模糊，',
  '注意力分散',
  '，態度不合',
  '作且敵對。',
  '當時精神病',
  '發作，精神',
  '恍惚。',
  '精神恍惚、',
  '<span style="font-size: 3em;">疑神疑鬼</span>。',
  '當時我拿打',
  '火機玩<span style="color: #F85F5F">火，</span>',
  '因生病沒有',
  '錢，跟家人',
  '要錢沒有給',
  '我。',
]

root.render(<DroppingText textArr={mockTextArr} />)
